export const SPORT_CONFIG = {
  17: { order: 1, dates: "Jan - Dec", name: "MMA" },
  12: { order: 2, dates: "Jan - Nov", name: "Men's Tennis" },
  13: { order: 3, dates: "Jan - Nov", name: "Women's Tennis" },
  14: { order: 4, dates: "Jan - Aug", name: "PGA Golf" },
  15: { order: 5, dates: "Jan - Nov", name: "LPGA Golf" },
  6: { order: 6, dates: "Feb - Dec", name: "MLS" },
  16: { order: 7, dates: "Mar - Dec", name: "Formula 1" },
  4: { order: 8, dates: "Mar - Nov", name: "MLB" },
  2: { order: 9, dates: "May - Oct", name: "WNBA" },
  7: { order: 10, dates: "Aug - Dec", name: "NCAAW Volleyball" },
  8: { order: 11, dates: "Aug - May", name: "Premier League" },
  9: { order: 12, dates: "Aug - Jan", name: "College Football" },
  3: { order: 13, dates: "Sep - Feb", name: "NFL" },
  1: { order: 14, dates: "Oct - Jun", name: "NBA" },
  5: { order: 15, dates: "Oct - Jun", name: "NHL" },
  10: { order: 16, dates: "Nov - Apr", name: "Men's CBB" },
  11: { order: 17, dates: "Nov - Apr", name: "Women's CBB" },
};
